org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
group=io.github.milkdrinkers
version=0.6.0
description=A Bolt addon adding GUI's & and other UX features to the Bolt plugin.
authors=ShermansWorld, darksaid98
contributors=
SONATYPE_CLOSE_TIMEOUT_SECONDS=1800
